### PR TITLE
adding linux aarch64 + ppc64le

### PR DESCRIPTION
**Pull request by ngam**
Just testing aarch64+ppc64le

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Looks like missing deps:
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-ppc64le: {MatchSpec("containers-common"), MatchSpec("btrfs-progs"), MatchSpec("libdevmapper")}
```

**Comment by ngam** [comment]
> Looks like missing deps:
> 
> ```
> conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-ppc64le: {MatchSpec("containers-common"), MatchSpec("btrfs-progs"), MatchSpec("libdevmapper")}
> ```

yep... 


https://github.com/conda-forge/libdevmapper-feedstock/pull/1#issuecomment-991444946

**Comment by ngam** [comment]
shoulda maybe asked a bot to do this rather than manually...

**Comment by ngam** [comment]
Ok. this is not gonna work, will add this to the migrator instead here (https://github.com/conda-forge/conda-forge-pinning-feedstock/tree/master/recipe/migrations)

closing, sorry for the disruption lol

**Comment by dhirschfeld** [comment]
> *sorry for the disruption*

Nothing to apologise about - thanks for giving it a go!

I think it will need to be added to the migrator but I'm not fully across that process myself. Happy for you to try though! :+1:

**Comment by ngam** [comment]
Thanks! The first dep seems to have gone through: 

https://github.com/conda-forge/libdevmapper-feedstock/pull/1

**Comment by ngam** [comment]
Other dep is also done: https://github.com/conda-forge/containers-common-feedstock/pull/9

**Pull request closed without merging**
